[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000"
TEXLIVE_URL = "http://localhost:5001/build"
NEXT_PUBLIC_ORCHESTRATOR_URL = "http://localhost:4000"
