# DigitalOcean App Platform Deployment
version: '3.8'

services:
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ORCHESTRATOR_URL=http://orchestrator:4000
    depends_on:
      - orchestrator
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - TEXLIVE_URL=http://texlive:5001/build
    volumes:
      - ./resume:/workspace/resume:ro
      - ./data:/workspace/data
      - ./scripts:/workspace/scripts:ro
    depends_on:
      - texlive
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  texlive:
    build:
      context: ./texlive
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./resume:/workspace/resume:ro
      - ./data:/workspace/data
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
